# SPDX-License-Identifier: GPL-2.0-only

snd-soc-sdca-y	:= sdca_functions.o sdca_device.o sdca_regmap.o

obj-$(CONFIG_SND_SOC_SDCA)	+= snd-soc-sdca.o

snd-soc-sdca-irq-handler-y	:= sdca_interrupts.o

obj-$(CONFIG_SND_SOC_SDCA_IRQ_HANDLER)	+= snd-soc-sdca-irq-handler.o
